inherit_from:
  - ./config/default.yml
  - ./config/rails.yml

Naming/FileName:
  Enabled: true
  Exclude:
    - "rubocop-inhouse.gemspec"
    - "lib/rubocop-inhouse.rb"
    - "lib/rubocop-inhouse-rails.rb"
