require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake

inherit_mode:
  merge:
    - Exclude

inherit_from:
  - ./layout.yml
  - ./lint.yml
  - ./style.yml
  - ./metrics.yml
  - ./rspec.yml
  - ./performance.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "data/**/*"
    - "**/bin/*"
    - "**/db/migrate/*.rb"
    - "**/db/schema.rb"
    - "**/node_modules/**/*"

# ====  GEMSPEC ====
Gemspec/DeprecatedAttributeAssignment:
  Enabled: true

Gemspec/DevelopmentDependencies:
  Enabled: true

Gemspec/RequireMFA:
  Enabled: true

# ====  NAMING  ====
Naming/BlockForwarding:
  Enabled: true
  EnforcedStyle: explicit

# ====  SECURITY  ====
Security/CompoundHash:
  Enabled: true

Security/IoMethods:
  Enabled: true
