Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_block
  Exclude:
    - "**/*.erb"

Layout/ClassStructure:
  ExpectedOrder:
    - module_inclusion
    - constants
    - association
    - public_attribute_macros
    - public_delegate
    - macros
    - initializer
    - public_class_methods
    - public_methods
    - protected_attribute_macros
    - protected_methods
    - private_attribute_macros
    - private_delegate
    - private_methods

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstMethodParameterLineBreak:
  Enabled: true

Layout/IndentationWidth:
  Exclude:
    - "**/*.erb"

Layout/InitialIndentation:
  Exclude:
    - "**/*.erb"

Layout/LineContinuationSpacing:
  Enabled: true

Layout/LineContinuationLeadingSpace:
  Enabled: true
  EnforcedStyle: trailing

Layout/LineEndStringConcatenationIndentation:
  Enabled: true

Layout/LineLength:
  Max: 80
  Exclude:
    - '**/spec/**/*'

Layout/MultilineArrayBraceLayout:
  EnforcedStyle: new_line

Layout/MultilineArrayLineBreaks:
  Enabled: true

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: same_line

Layout/MultilineHashBraceLayout:
  EnforcedStyle: new_line

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true
  AllowMultilineFinalElement: true

Layout/MultilineMethodCallBraceLayout:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/SpaceInsideParens:
  Exclude:
    - "**/*.erb"

Layout/MultilineMethodDefinitionBraceLayout:
  EnforcedStyle: new_line

Layout/MultilineMethodParameterLineBreaks:
  Enabled: true

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/SingleLineBlockChain:
  Enabled: true

Layout/SpaceBeforeBrackets:
  Enabled: true

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_no_space

Layout/TrailingEmptyLines:
  Exclude:
    - "**/*.erb"

Layout/TrailingWhitespace:
  Exclude:
    - "**/*.erb"
