Metrics/AbcSize:
  Max: 20
  CountRepeatedAttributes: false
  # Excluding controllers here because respond_to blocks and others make this
  # higher than they otherwise should be
  Exclude:
    - "**/app/controllers/**/*"

Metrics/BlockLength:
  CountComments: false
  Max: 25
  Exclude:
    - "**/spec/**/*"
    - "**/*.rake"
    - "**/factories/**/*"
    - "**/config/**/*"

Metrics/CollectionLiteralLength:
  Enabled: true

Metrics/ClassLength:
  CountAsOne: ["array", "hash"]
  Max: 100
  Exclude:
    - "**/app/controllers/**/*"

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  CountAsOne: ["array", "hash", "method_call"]
  Max: 20

Metrics/ModuleLength:
  CountAsOne: ["array", "hash"]
  Max: 100
  Exclude:
    - "**/spec/**/*"

Metrics/ParameterLists:
  Max: 2
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Max: 8

