Metrics/AbcSize:
  Max: 20
  CountRepeatedAttributes: false
  # Excluding controllers here because respond_to blocks and others make this
  # higher than they otherwise should be
  Exclude:
    - "**/app/controllers/**/*"
    - "**/app/views/**/*.rb"

Metrics/BlockLength:
  CountComments: false
  Max: 25
  Exclude:
    - "**/spec/**/*.rb"
    - "**/config/**/*.rb"
    - "**/app/views/**/*.rb"
    - "**/lib/tasks/**/*.rake"
    - "**/*.rake"

Metrics/CollectionLiteralLength:
  Enabled: true

Metrics/ClassLength:
  CountAsOne: ["array", "hash"]
  Max: 100
  Exclude:
    - "**/app/controllers/**/*.rb"
    - "**/app/views/**/*.rb"

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  CountAsOne: ["array", "hash", "method_call"]
  Max: 20
  Exclude:
    - "**/app/views/**/*.rb"

Metrics/ModuleLength:
  CountAsOne: ["array", "hash"]
  Max: 100
  Exclude:
    - "**/spec/**/*.rb"

Metrics/ParameterLists:
  Max: 2
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Max: 8
  Exclude:
    - "**/app/views/**/*.rb"
