plugins:
  - rubocop-rails
  - rubocop-factory_bot
  - rubocop-capybara
  - rubocop-rspec_rails

inherit_from:
  - ./capybara.yml
  - ./factory_bot.yml

Rails/ActionFilter:
  Enabled: true

Rails/ActiveRecordCallbacksOrder:
  Enabled: true

Rails/AfterCommitOverride:
  Enabled: true

Rails/ActionControllerTestCase:
  Enabled: false

Rails/ActionControllerFlashBeforeRender:
  Enabled: true

Rails/ActionOrder:
  Enabled: true

Rails/ActiveSupportOnLoad:
  Enabled: true

Rails/AddColumnIndex:
  Enabled: true

# Prefer assert_not over assert !
Rails/AssertNot:
  Include:
    - "test/**/*"

# Prefer assert_not_x over refute_x
Rails/RefuteMethods:
  Include:
    - "test/**/*"

Rails/AttributeDefaultBlockValue:
  Enabled: true

Rails/CompactBlank:
  Enabled: true

Rails/DangerousColumnNames:
  Enabled: true

Rails/DeprecatedActiveModelErrorsMethods:
  Enabled: false

Rails/DotSeparatedKeys:
  Enabled: true

Rails/DuplicateAssociation:
  Enabled: true

Rails/DuplicateScope:
  Enabled: true

Rails/DurationArithmetic:
  Enabled: true

Rails/EagerEvaluationLogMessage:
  Enabled: true

Rails/EnvLocal:
  Enabled: true

Rails/ExpandedDateRange:
  Enabled: true

Rails/FreezeTime:
  Enabled: true

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/Date:
  Enabled: true
  EnforcedStyle: strict

Rails/Delegate:
  Enabled: true

Rails/DefaultScope:
  Enabled: true

Rails/FindById:
  Enabled: true

Rails/I18nLazyLookup:
  Enabled: true

Rails/I18nLocaleAssignment:
  Enabled: true

Rails/I18nLocaleTexts:
  Enabled: true

Rails/IgnoredColumnsAssignment:
  Enabled: true

Rails/Inquiry:
  Enabled: true

Rails/MigrationClassName:
  Enabled: true

Rails/MailerName:
  Enabled: true

Rails/MatchRoute:
  Enabled: true

Rails/NegateInclude:
  Enabled: true

Rails/OrderById:
  Enabled: true

Rails/Output:
  Exclude:
    - "**/app/views/**/*.rb"

Rails/Pluck:
  Enabled: true

Rails/PluckId:
  Enabled: true

Rails/PluckInWhere:
  Enabled: true

Rails/RenderInline:
  Enabled: true

Rails/RenderPlainText:
  Enabled: true

Rails/RedundantActiveRecordAllMethod:
  Enabled: true

Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: true

Rails/RedundantTravelBack:
  Enabled: true

Rails/ResponseParsedBody:
  Enabled: true

Rails/RootJoinChain:
  Enabled: true

Rails/RootPublicPath:
  Enabled: true

Rails/RootPathnameMethods:
  Enabled: true

Rails/SaveBang:
  Enabled: true
  AllowImplicitReturn: false
  Exclude:
    - "**/spec/**/*.rb"
    - "**/config/**/*.rb"
    - "**/lib/**/*.rb"

Rails/ShortI18n:
  Enabled: true

Rails/SquishedSQLHeredocs:
  Enabled: true

Rails/StripHeredoc:
  Enabled: true

Rails/ThreeStateBooleanColumn:
  Enabled: true

Rails/TimeZoneAssignment:
  Enabled: true

Rails/ToFormattedS:
  Enabled: true

Rails/ToSWithArgument:
  Enabled: true

Rails/TopLevelHashWithIndifferentAccess:
  Enabled: true

Rails/TransactionExitStatement:
  Enabled: true

Rails/UnusedIgnoredColumns:
  Enabled: true

Rails/UnusedRenderContent:
  Enabled: true

Rails/WhereEquals:
  Enabled: true

Rails/WhereMissing:
  Enabled: true

Rails/WhereNotWithMultipleConditions:
  Enabled: true



Rails/WhereExists:
  Enabled: true

Rails/WhereNot:
  Enabled: true

RSpecRails/AvoidSetupHook:
  Enabled: true

RSpecRails/HaveHttpStatus:
  Enabled: true

RSpecRails/InferredSpecType:
  Enabled: true

RSpecRails/MinitestAssertions:
  Enabled: true

RSpecRails/NegationBeValid:
  Enabled: true

RSpecRails/TravelAround:
  Enabled: true
