RSpec/BeEq:
  Enabled: true

RSpec/BeEmpty:
  Enabled: true

RSpec/BeNil:
  Enabled: true

RSpec/DuplicatedMetadata:
  Enabled: true

RSpec/ChangeByZero:
  Enabled: true

RSpec/ContainExactly:
  Enabled: true

RSpec/EmptyMetadata:
  Enabled: true

RSpec/Eq:
  Enabled: true

RSpec/ExcessiveDocstringSpacing:
  Enabled: true

RSpec/IdenticalEqualityAssertion:
  Enabled: true

RSpec/IndexedLet:
  Enabled: true

RSpec/MatchArray:
  Enabled: true

RSpec/MetadataStyle:
  Enabled: true

RSpec/NoExpectationExample:
  Enabled: true

RSpec/PendingWithoutReason:
  Enabled: true

RSpec/ReceiveMessages:
  Enabled: true

RSpec/RedundantAround:
  Enabled: true

RSpec/SkipBlockInsideExample:
  Enabled: true

RSpec/SortMetadata:
  Enabled: true

RSpec/SpecFilePathSuffix:
  Enabled: true

RSpec/SubjectDeclaration:
  Enabled: true

RSpec/VerifiedDoubleReference:
  Enabled: true

RSpec/SpecFilePathFormat:
  Enabled: true
  Exclude:
    - "spec/factories/**/*.rb"
    - "spec/components/**/*.rb"

RSpec/MissingExampleGroupArgument:
  Enabled: true
  Exclude:
    - 'spec/factories/**/*.rb'

RSpec/EmptyExampleGroup:
  Enabled: true
  Exclude:
    - 'spec/factories/**/*.rb'

RSpec/AnyInstance:
  Enabled: false
  Exclude:
    - 'spec/factories/**/*.rb'

RSpec/BeforeAfterAll:
  Enabled: false
  Exclude:
    - 'spec/factories/**/*.rb'

RSpec/ContextWording:
  Enabled: false
  Exclude:
    - 'spec/factories/**/*.rb'

RSpec/DescribeClass:
  Enabled: false
  Exclude:
    - 'spec/factories/**/*.rb'

RSpec/ExampleLength:
  Enabled: false
  Exclude:
    - 'spec/factories/**/*.rb'

RSpec/ExpectInHook:
  Enabled: false
  Exclude:
    - 'spec/factories/**/*.rb'

RSpec/FilePath:
  Enabled: false
  Exclude:
    - 'spec/factories/**/*.rb'

RSpec/InstanceVariable:
  Enabled: false
  Exclude:
    - 'spec/factories/**/*.rb'

RSpec/LetSetup:
  Enabled: false
  Exclude:
    - 'spec/factories/**/*.rb'

RSpec/MessageChain:
  Enabled: false
  Exclude:
    - 'spec/factories/**/*.rb'

RSpec/MessageSpies:
  Enabled: false
  Exclude:
    - 'spec/factories/**/*.rb'

RSpec/MultipleExpectations:
  Enabled: false
  Exclude:
    - 'spec/factories/**/*.rb'

RSpec/NamedSubject:
  Enabled: false
  Exclude:
    - 'spec/factories/**/*.rb'

RSpec/NestedGroups:
  Max: 7
  Exclude:
    - 'spec/factories/**/*.rb'

RSpec/SubjectStub:
  Enabled: false
  Exclude:
    - 'spec/factories/**/*.rb'

RSpec/VerifiedDoubles:
  Enabled: false
  Exclude:
    - 'spec/factories/**/*.rb'

RSpec/VoidExpect:
  Enabled: false
  Exclude:
    - 'spec/factories/**/*.rb'

