RSpec/BeEq:
  Enabled: true

RSpec/BeEmpty:
  Enabled: true

RSpec/BeNil:
  Enabled: true

RSpec/DuplicatedMetadata:
  Enabled: true

RSpec/ChangeByZero:
  Enabled: true

RSpec/ContainExactly:
  Enabled: true

RSpec/EmptyMetadata:
  Enabled: true

RSpec/Eq:
  Enabled: true

RSpec/ExcessiveDocstringSpacing:
  Enabled: true

RSpec/IdenticalEqualityAssertion:
  Enabled: true

RSpec/IndexedLet:
  Enabled: true

RSpec/MatchArray:
  Enabled: true

RSpec/MetadataStyle:
  Enabled: true

RSpec/NoExpectationExample:
  Enabled: true

RSpec/PendingWithoutReason:
  Enabled: true

RSpec/ReceiveMessages:
  Enabled: true

RSpec/RedundantAround:
  Enabled: true

RSpec/SkipBlockInsideExample:
  Enabled: true

RSpec/SortMetadata:
  Enabled: true

RSpec/SpecFilePathSuffix:
  Enabled: true

RSpec/SubjectDeclaration:
  Enabled: true

RSpec/VerifiedDoubleReference:
  Enabled: true

RSpec/SpecFilePathFormat:
  Enabled: true
  Exclude:
    - "**/spec/factories/*"
    - "**/spec/components/**/*"

RSpec/MissingExampleGroupArgument:
  Enabled: true
  Exclude:
    - '**/spec/factories/*'

RSpec/EmptyExampleGroup:
  Enabled: true
  Exclude:
    - '**/spec/factories/*'

RSpec/AnyInstance:
  Enabled: false
  Exclude:
    - '**/spec/factories/*'

RSpec/BeforeAfterAll:
  Enabled: false
  Exclude:
    - '**/spec/factories/*'

RSpec/ContextWording:
  Enabled: false
  Exclude:
    - '**/spec/factories/*'

RSpec/DescribeClass:
  Enabled: false
  Exclude:
    - '**/spec/factories/*'

RSpec/ExampleLength:
  Enabled: false
  Exclude:
    - '**/spec/factories/*'

RSpec/ExpectInHook:
  Enabled: false
  Exclude:
    - '**/spec/factories/*'

RSpec/FilePath:
  Enabled: false
  Exclude:
    - '**/spec/factories/*'

RSpec/InstanceVariable:
  Enabled: false
  Exclude:
    - '**/spec/factories/*'

RSpec/LetSetup:
  Enabled: false
  Exclude:
    - '**/spec/factories/*'

RSpec/MessageChain:
  Enabled: false
  Exclude:
    - '**/spec/factories/*'

RSpec/MessageSpies:
  Enabled: false
  Exclude:
    - '**/spec/factories/*'

RSpec/MultipleExpectations:
  Enabled: false
  Exclude:
    - '**/spec/factories/*'

RSpec/NamedSubject:
  Enabled: false
  Exclude:
    - '**/spec/factories/*'

RSpec/NestedGroups:
  Max: 7
  Exclude:
    - '**/spec/factories/*'

RSpec/SubjectStub:
  Enabled: false
  Exclude:
    - '**/spec/factories/*'

RSpec/VerifiedDoubles:
  Enabled: false
  Exclude:
    - '**/spec/factories/*'

RSpec/VoidExpect:
  Enabled: false
  Exclude:
    - '**/spec/factories/*'

RSpec/Rails/AvoidSetupHook:
  Enabled: true

RSpec/Rails/HaveHttpStatus:
  Enabled: true

RSpec/Rails/InferredSpecType:
  Enabled: true

RSpec/Rails/MinitestAssertions:
  Enabled: true

RSpec/Rails/NegationBeValid:
  Enabled: true

RSpec/Rails/TravelAround:
  Enabled: true
